controller:
  adminPassword: "admin"
  installPlugins:
    - kubernetes:4.2.1
    - workflow-aggregator:590.v6a_d052e5a_a_b_5
    - git:5.2.1
    - configuration-as-code:1775.v810dc950b_514
persistence:
  enabled: true
  size: "8Gi"
