pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["sleep", "9999999"]
  - name: git
    image: alpine/git
    command: ["sleep", "9999999"]
'''
        }
    }
    environment {
        ECR_REPO = "AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/lesson-8-ecr"
        GIT_REPO = "https://github.com/YOUR_GITHUB_USER/YOUR_REPO_NAME.git"
    }
    stages {
        stage('Build & Push (Kaniko)') {
            steps {
                container('kaniko') {
                    // Збірка і пуш Docker-образу
                    sh '/kaniko/executor --context `pwd` --dockerfile `pwd`/Dockerfile --destination ${ECR_REPO}:${BUILD_NUMBER}'
                }
            }
        }
        stage('Update Git (Helm Chart)') {
            steps {
                container('git') {
                    // Оновлення тегу в values.yaml
                    sh '''
                        git clone ${GIT_REPO} repo
                        cd repo/charts/django-app
                        sed -i "s/tag: .*/tag: \"${BUILD_NUMBER}\"/" values.yaml
                        git config user.name "Jenkins CI"
                        git config user.email "jenkins@ci.local"
                        git add values.yaml
                        git commit -m "Update image tag to ${BUILD_NUMBER}"
                        git push origin main
                    '''
                }
            }
        }
    }
}
