image:
  repository: AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/lesson-7-ecr
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  DJANGO_SETTINGS_MODULE: "my_project.settings"
  DEBUG: "False"
  POSTGRES_DB: "django_db"
  POSTGRES_USER: "admin"
